packages:
  - .
allowBuilds:
  '@sentry/cli': set this to true or false
  esbuild: true
  sharp: set this to true or false
  unrs-resolver: false
excludeDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
