packages:
  - .
excludeDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
