/**
 * Data constants for the GlobalInfrastructure component.
 *
 * Marker positions are no longer computed here: the region visualizations
 * consume pre-projected geometry from `src/data/product/regionGeometry.ts`
 * (generated by `pnpm geometry:regions`). REGION_COORDS remains the source of
 * truth for the datacenter locations and is read at runtime by the rotating
 * globe, which projects them per frame.
 */

export interface TrustBadge {
  readonly key: string;
}

export interface RegionCoord {
  readonly label: string;
  readonly lat: number; // degrees, positive = North
  readonly lon: number; // degrees, positive = East
}

export const trustBadges: readonly TrustBadge[] = [
  { key: "web.homepage.infrastructure.regions.ca" },
  { key: "web.homepage.infrastructure.regions.eu" },
  { key: "web.homepage.infrastructure.regions.nz" },
  { key: "web.homepage.infrastructure.regions.uk" },
  { key: "web.homepage.infrastructure.regions.us" },
] as const;

/** Real datacenter cities. Mirrored in `scripts/generate-region-geometry.mjs`
 *  — update both together. */
export const REGION_COORDS: readonly RegionCoord[] = [
  { label: "CA", lat: 43.65, lon: -79.38 }, // Toronto
  { label: "EU", lat: 49.45, lon: 11.08 }, // Nuremberg
  { label: "NZ", lat: -41.13, lon: 174.84 }, // Porirua
  { label: "UK", lat: 51.51, lon: -0.13 }, // London
  { label: "US", lat: 45.52, lon: -122.99 }, // Hillsboro
];
